candidate_information: >
  # João Silva
  **Desenvolvedor Full Stack**

  Email: joao.silva@email.com | Telefone: +55 11 98765-4321  
  LinkedIn: [João Silva](https://www.linkedin.com/in/joao-silva) | GitHub: [joaosilva](https://github.com/joaosilva)

  ## Resumo
  Desenvolvedor Full Stack com 5 anos de experiência em desenvolvimento de software, com forte conhecimento em JavaScript, Node.js e React. 
  Apaixonado por aprender novas tecnologias e melhorar processos de desenvolvimento.

  ## Habilidades
  - JavaScript, Node.js, React, HTML5, CSS3
  - SQL, Git, Docker, Agile/Scrum
  - Desenvolvimento ágil e trabalho em equipe

  ## Experiência

  **Desenvolvedor Full Stack**  
  *Tech Solutions Ltda* | Jan 2022 - Presente  
  - Desenvolvimento de aplicações web com React e Node.js.
  - Manutenção de sistemas legados e otimização de performance.
  - Colaboração com as equipes de design e backend.

  **Desenvolvedor Front-End**  
  *Web Innovators* | Jul 2019 - Dez 2021  
  - Criação de interfaces responsivas utilizando React.
  - Integração de APIs e garantia de performance.

  ## Educação
  **Bacharelado em Ciência da Computação**  
  *Universidade de São Paulo (USP)* | 2015 - 2019

  ## Certificações
  - Certificação React - Coursera (2020)
  - Certificação Node.js - Udemy (2021)

candidate_objectives: >
  Busco uma oportunidade para atuar como Desenvolvedor Full Stack, onde possa aplicar meus conhecimentos em JavaScript, Node.js e React, 
  enquanto continuo aprendendo e contribuindo para o crescimento de projetos desafiadores. Meu objetivo é trabalhar em um ambiente dinâmico, 
  que valorize o trabalho em equipe e a inovação tecnológica.
